apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "details"
  title: "details"
  description: "Details API"
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/bookinfo/spectral-rules/main/ruleset.yaml
  links:
    - url: https://registry-apicurio-registry.apps.cluster-zpqtb.zpqtb.sandbox2275.opentlc.com/ui/artifacts/com.redhat.demo.bookinfo/details/versions/latest
      title: Apicurio Registry
      icon: web
    - url: https://microcks-microcks.apps.cluster-zpqtb.zpqtb.sandbox2275.opentlc.com/#/services?name=details
      title: Microcks
    - url: https://microcks-microcks.apps.cluster-zpqtb.zpqtb.sandbox2275.opentlc.com/rest/details/v1
      title: Mock
      icon: web
spec:
  type: openapi
  system: system:default/bookinfo
  owner: group:default/backstage-admins
  lifecycle: production
  definition:
    $openapi: https://github.com/contract-first-idp-test/bookinfo-details-api/blob/main/specification.yaml